broadinstitute/palantir-workflows

BenchmarkVCFs/BenchmarkVCFs.wdl
BenchmarkVCFs/README.md
BenchmarkVCFs/test.json

@yfarjoun could you approve initial check-in.  Once it's in we can start applying updates here.

Benchmarking workflow initial check-in

---

ImputationPipeline/ScoringPart.wdl
ImputationPipeline/flashpca_docker/Dockerfile

@edytamalolepsza this is the fix to allow to run in single sample mode

FlashPCA projection fix for single sample Projection

---

.dockstore.yml
BenchmarkVCFs/BenchmarkVCFs.wdl
README.md

Dockstore's Github App has arrived!

---

ImputationPipeline/Imputation.wdl
ImputationPipeline/ScoringPart.wdl

Adds qc metrics output for imputation pipelie.

Output metrics from imputation pipeline

---

ImputationPipeline/ScoringPart.wdl

honestly, I'm surprised cromwell never threw an error parsing this.

Remove duplicate input in PRS scoring wdl

---

ImputationPipeline/Imputation.wdl

Recover sites from original array which do not make it through imputation (due to qc removal and missing from reference panel).

Recover sites from original array

---

ImputationPipeline/Imputation.wdl

Make memory allocation for task a commandline argument.

Added option for memory allocation for MergeSingleSampleVcfs task

---

ImputationPipeline/ScoringPart.wdl

Moved R script contents to a "heredoc". 
Tested functional equivalent by diffing output from scoring pipeline in main vs in this branch.

Replaced adjustscores call to google bucket script with Heredoc

---

BenchmarkVCFs/shinyApp/README.md
BenchmarkVCFs/shinyApp/app.R
BenchmarkVCFs/shinyApp/download.R
BenchmarkVCFs/shinyApp/loadData.R
BenchmarkVCFs/shinyApp/plotClicks.R
BenchmarkVCFs/shinyApp/plots.R
BenchmarkVCFs/shinyApp/selectData.R
BenchmarkVCFs/shinyApp/server.R
BenchmarkVCFs/shinyApp/tableClicks.R
BenchmarkVCFs/shinyApp/tables.R
BenchmarkVCFs/shinyApp/tabsEnum.R
BenchmarkVCFs/shinyApp/ui.R
BenchmarkVCFs/shinyApp/uiControl.R

I moved this from our private "palantir" repository and made a few changes so that it works in the presence of multiple inputs (vcfs) and multiple interval lists. 
would be nice to (eventually) publish this directly from github using a more generic credential, rather than it being on my personal account.....

making the BenchmarkVcf shiny app public

---

BenchmarkVCFs/BenchmarkVCFs.wdl

@jamesemery this is the fix we just discussed

Using write_lines to avoid bash character line limits

---

ImputationPipeline/ScoringPart.wdl

Reverts broadinstitute/palantir-workflows#35

Revert "Replaced adjustscores call to google bucket script with Heredoc"

---

ImputationPipeline/ScoringPart.wdl

Changed "<<-" to "- <<-" (who came up with bash syntax, seriously…)

Fix Rscript heredoc syntax

---

ImputationPipeline/Validation/ValidateImputation.wdl

@tmelman this was the bug that used a "<" instead of "<=" in the if statement

Fixes bug in validation workflow

---

ImputationPipeline/ScoringPart.wdl

Fixed syntax error preventing this from running

Fix syntax error in Scoringpart.wdl

---

ImputationPipeline/ScoringPart.wdl

Ugh. I don't know how I lost the output portion of the R script, but I fixed it. I hope.

Restore outputs to Rscript in AdjustScores task

---

ImputationPipeline/EndToEndPipeline.wdl
ImputationPipeline/ScoringPart.wdl
ImputationPipeline/Validation/FullImputationPRSValidation.wdl
ImputationPipeline/Validation/ValidateScoring.wdl

also adds testing for when score adjustment is turned off
score adjustments off validation
score adjustment on validation

Make score adjustment optional

---

ImputationPipeline/ScoringPart.wdl
ImputationPipeline/Validation/ValidateImputation.wdl

In PRS scoring set all ids using plink instead of relying on input ids

---

ImputationPipeline/ScoringPart.wdl
ImputationPipeline/Validation/ValidateScoring.wdl

Addresses #50 
We will want to wait until after discussions with eMerge prs wg before merging this change.

PRS ancestry dependent var adjustment 

---

ImputationPipeline/ScoringPart.wdl

Add log link to estimate of variance

Tm loglink population correction

---

ImputationPipeline/PRSWrapper.wdl

@edytamalolepsza need this for production test

Add percentile to output of prs wrapper

---

ImputationPipeline/PRSWrapper.wdl

@edytamalolepsza this is the quick pr I was talking about at the meeting yesterday

Switch PRS wrapper "risk" output to HIGH/NOT_HIGH string instead of boolean

---

ImputationPipeline/CKDRiskAdjustment.wdl

A very small change so that CKDRiskAdjustment can be run on wgs

Add --allow-extra-chr to GenotypeG1G2RiskAlleles

---

ImputationPipeline/AggregatePRSResults.wdl
ImputationPipeline/PRSWrapper.wdl
ImputationPipeline/ScoringPart.wdl
ImputationPipeline/ScoringTasks.wdl
ImputationPipeline/Validation/ValidateScoring.wdl

Checks if any sites used for training of ancestry model are missing.  If there are missing sites, calculates possible shift due to missing sites.  Include missing site info in aggregated qc report.

PRS missing sites QC

---

ImputationPipeline/PCATasks.wdl
ImputationPipeline/ScoringTasks.wdl
ImputationPipeline/Validation/ValidateScoring.wdl
ImputationPipeline/plink2_docker/Dockerfile

Over 11 conditions over 42 samples, largest difference in z-score was 8.06e-9.

Remove personal dockers in PRS pipeline

---

ImputationPipeline/AggregatePRSResults.wdl
ImputationPipeline/tidyverse_kableextra_docker/Dockerfile
LICENSE

Based on requests/comments from @edytamalolepsza.

Formatting improvements to aggregation report

---

FunctionalEquivalence/FunctionalEquivalence.wdl
FunctionalEquivalence/subworkflows/F1Evaluation.wdl

- New (more correct) calculation of the F1 scores at each sampling position (this solves the issue of "gaps" in the plots)
- Automatic detection of the stratifiers

FE: rewrote F1 evaluation using Pandas

---

ImputationPipeline/AggregatePRSResults.wdl

A few improvements to PRS QC report:
1. Removes control sample from batch summary table and batch score distribution plot
2. Adds table of individuals who are high in more than one condition
3. Batch score distribution plot is now interactive plotly plot
4. Batch score distribution uses data points on x axis instead of density distribution for conditions with fewer than 5 samples
5. Adds column of  number of high conditions for each individual in individual samples table, so that can sort individuals by this

QC Report updates

---

FunctionalEquivalence/FunctionalEquivalence.wdl
FunctionalEquivalence/docker/fe_evaluation/Dockerfile
FunctionalEquivalence/docker/fe_evaluation/environment.yml
FunctionalEquivalence/subworkflows/F1Evaluation.wdl
FunctionalEquivalence/subworkflows/FEEvaluation.wdl
FunctionalEquivalence/subworkflows/PlotROC.wdl
Utilities/Dockers/Python-Data-Slim-Plots/dockerfile
Utilities/Dockers/Python-Data-Slim/dockerfile
Utilities/Dockers/README.md

Fixes bug where pandas was not installed in the FE evaluation dockers

Updated python-data-slim and using it in FunctionalEquivalence WDLs

---

.dockstore.yml
Utilities/WDLs/DownsampleAndCollectCoverage.wdl
Utilities/WDLs/README.md

New Utilities WDL: DownsampleAndCollectCoverage

---

ImputationPipeline/PCATasks.wdl
ImputationPipeline/PerformPopulationPCA.wdl
ImputationPipeline/ScoringTasks.wdl

Regarding issues #147 #148 and #149

Potential improvements regarding default thread numbers and disk sizes.

---

ImputationPipeline/CreateAggregationSets/CreateAggregationSets.py
ImputationPipeline/ManualQCPRS/ManualQCPRS.py

- Also skipping blank samples when creating aggregation sets

Fixed error in CreateAggregationSets when reading booleans as strings

---

ImputationPipeline/ScoreBGE/ScoreBGE.py
ImputationPipeline/ScoreBGE/ScoreBGE.wdl

Arguments can't be inserted in Python file but must be passed to the Python script

Fix for ScoreBGE

---

ImputationPipeline/PerformPopulationPCA.wdl
ImputationPipeline/ScoringPart.wdl
ImputationPipeline/TrainAncestryAdjustmentModel.wdl

Just fixing a few whitespaces places from from my last comment in #189. @kachulis

Fix whitespace in some recent changes

---

.github/workflows/run_tests.yaml
Utilities/WDLs/IntervalList2Bed.wdl

should help tests pass more reliably on GCPBATCH

Bump cromwell version to 89 for tests
