broadinstitute/palantir-workflows

ImputationPipeline/EndToEndPipeline.wdl, ImputationPipeline/PerformPopulationPCA.wdl, ImputationPipeline/ScoringPart.wdl
This PR improves our implementation of using only typed sites for PCA, which had been our objective in the past, but had not been perfectly implemented.  Also adds the ability to redo the PCA calculation when scoring a sample, and also enforces that population scoring is done only over sites genotyped in the sample.  This is needed in a situation where the different samples may not have genotyped exactly all of the same sites, such as when scoring a wgs.
=> PCA on typed sites only, allow for redoing pca in scoring

ImputationPipeline/Imputation.wdl, ImputationPipeline/PerformPopulationPCA.wdl
RemoveMultiallelics is a major bottleneck when running on large cohorts (1000+ samples) due to a regression which was fixed in broadinstitute/gatk#6729
This change takes advantage of the fix by bumping gatk version on SelectVariants tasks.  I expect a fairly massive time and money savings on large cohorts.
Additional optimization will be available by bumping the version again once broadinstitute/gatk#6754 is merged.
=> Massive speedup on large cohorts

BenchmarkVCFs/BenchmarkVCFs.wdl
I was getting timeout errors from pulling the gatk docker from dockerhub. Using google instead should fix that.
=> Use gcr instead of dockerhub in Benchmarking wdl

ImputationPipeline/Validation/ValidateScoring.wdl
Current iteration of pipeline fails in circleCI due to a missing `selectfirst`. Here's a proposed fix.
=> Fix validation workflow bug

ImputationPipeline/ScoringPart.wdl
we need to make sure plink is given a memory argument that is less than the total memory given to the machine
=> Score vcf memory change

BenchmarkVCFs/BenchmarkVCFs.wdl
- In task MatchEvalTruth the disk size was not dependent on the input VCFs. Now, both the VCFs and their indices are considered.
- Fixes #70
=> BenchmarkVCFs: Added input VCFs to disk size determination

BenchmarkVCFs/FindSamplesAndBenchmark.wdl
This removes the extra copy of the parameter. This was introduced in #65
=> Accidentally added an extra parameter while rebasing a previous commit

ImputationPipeline/CKDRiskAdjustment.wdl
A no-call in the vcf will result in NA in the risk allele count file.  This pr then converts those NA's to 0, so treats no calls as 0 risk alleles.  
I haven't tested this yet at all, but I suspect the emerge 1-3 tests may hit this issue, so can be tested on that.
#61
=> Handle no-calls at APOl1 risk alleles in ckd adjustment

BenchmarkVCFs/BenchmarkVCFs.wdl
- If there are SNPs present but no INDELs, true will be passed to SummariseVcfEval and it is attempted to output the values to the files. That way, NA can be written to some files, which causes the workflow to fail.
- Added check if a value is NA, and if yes, output 0.
=> BenchmarkVCFs: Fixed a bug where NA is written to output files

ImputationPipeline/PRSWrapper.wdl
In PRSWrapper, If PRS z-scores is outside defined reportable range, results are changed to "NOT_RESULTED" and reason is recorded in "~{condition}_not_resulted_reason" column.
=> PRS Reportable Range Check

.dockstore.yml, ImputationPipeline/AggregatePRSResults.wdl, ImputationPipeline/PRSWrapper.wdl, ImputationPipeline/ScoringPart.wdl, ImputationPipeline/tidyverse_kableextra_docker/Dockerfile, ImputationPipeline/tidyverse_kableextra_docker/build_push_r_kableextra_docker.sh
- PRSWrapper.wdl
- Added columns `batch_id` and `is_control` to results.csv
- New file: AggregatePRSResults
- Aggregate multiple results CSV files into summarized tables
- Check that all `batch_id`s are the same
- Check that there is exactly one control sample within every batch
- Extract control sample
- Extract results in two shapes: `all_results` and `summarized_results`
- Extract score distribution
- Create population PCA plot
- Build HTML report
- Compare control sample to expected control result
- Batch summary
- Score distribution
- Population PCA
- Individual results
- Added to Dockstore.yml
- Fixed bug in ScoringPart.wdl
=> Aggregate PRS Output

ImputationPipeline/EndToEndPipeline.wdl, ImputationPipeline/PRSWrapper.wdl, ImputationPipeline/ScoringPart.wdl, ImputationPipeline/Structs.wdl, ImputationPipeline/Validation/ValidateScoring.wdl, ImputationPipeline/build_push_docker.sh, ImputationPipeline/imputation_interaction_python/Dockerfile
Adds interaction terms to the PRS pipeline.  For a listed interaction, each allele can only participate in the interactions once.  So, if a sample is het in one interaction allele, and hom in the other, it will have the 1x interaction weight added to the score.  If it is hom in both interaction alleles, it will have 2x interaction weight added.  And if it is het in one and doesn't contain the other, will not have the interaction weight added.  Additionally, if the two interaction alleles in the interaction are the same, then the interaction weight will be added if and only if the sample is hom in the interaction allele.
There is also a bit of a hack included here using the `SelfExclusiveSites`.  This is a set of alleles of which only a specified number are allowed to be included, or the …
=> Add Interaction terms to PRS pipeline 

ImputationPipeline/AggregatePRSResults.wdl
If control sample is not resulted for a condition, the column will be read as a character in the control table, which can then not be combined with the numeric in the expected control scores table.  To fix this, we can force all the values to be read as numerics in the control table, which will turn the non-numerics into NA's, which then get handled as desired by the rest of the cell.
@michaelgatzen this is not urgent, so just when you get around to it.
=> Handle situation where control sample is not resulted for one (or more) conditions

ImputationPipeline/AggregatePRSResults.wdl
This PR makes some improvements and fixes some bugs in the formatting of the samples table in the PRS aggregation report.  Specifically:
1. All condition related cells ({condition}_raw, {condition}_adj, etc) are now colored according the the risk status for that condition.
2. A bug is fixed so that all numerics are correctly rounded
3. NA (for scores that were not calculated) is replaced with "SCORE NOT REQUESTED", and colored light gray.
4. "_" is removed in string cells (so "NOT_RESULTED" become "NOT RESULTED" )
5. {condition}_adjusted is changed to {condition}_adj, to better fit more columns without needing to use the slider.
Note all of the changes are to display only.  The underlying data is not changed.
=> Improved formatting of samples table in prs aggregation report

.dockstore.yml, BenchmarkVCFs/BenchmarkBoard/BenchmarkBoard-MS.ipynb, BenchmarkVCFs/BenchmarkBoard/BenchmarkBoard-MS.py, BenchmarkVCFs/BenchmarkBoard/BenchmarkBoard-SS.ipynb, BenchmarkVCFs/BenchmarkBoard/BenchmarkBoard-SS.py, BenchmarkVCFs/BenchmarkBoard/BenchmarkBoard_README.md, BenchmarkVCFs/SimpleBenchmark.wdl, BenchmarkVCFs/SimpleBenchmark_README.md, Utilities/Dockers/BCFTools/Dockerfile, Utilities/Dockers/README.md, Utilities/Dockers/RTG/Dockerfile
This PR introduces a rewrite of the [BenchmarkVCFs](https://github.com/broadinstitute/palantir-workflows/blob/main/BenchmarkVCFs/BenchmarkVCFs.wdl) WDL used for comparing a VCF (callset) to a baseline (base) VCF. The main goals for this project were the following:
* **Speed up the runtime in Terra.** Typical runs of BenchmarkVCFs could take anywhere from 1-6 hours, whereas the core comparison done by vcfeval takes a small fraction of that time. The original impetus for this rewrite was to peel out the most necessary tasks required to automate the comparison, without sacrificing too much functionality.
* **Fix bugs and add extra functionality.** There was a bug in the previous code where arbitrary selection via jexl selectors did not work as advertised. This should be corrected now, using …
=> SimpleBenchmark -- a new WDL for benchmarking VCFs

Utilities/IntervalFiles/README.md
Just adds a comma to the list where it was missing so you can actually copy & paste into Terra.
=> Added missing comma in interval list input for Terra

Utilities/Dockers/README.md, Utilities/Dockers/Samtools/Dockerfile, Utilities/IntervalFiles/ComputeIntervalBamStats.wdl, Utilities/IntervalFiles/README.md
This PR includes a few additions and changes for computations over interval lists. The main components are:
* Added `ComputeIntervalBamStats.wdl`, which is a workflow that takes in a bam file, a list of interval lists, and some other metadata which computes Picard's CollectWgsMetrics on the bam over those intervals, along with a mapping quality distribution for each region. These statistics are then collected and labeled over the groups into a few output tsvs that are ready to be visualized (dashboard coming soon, maybe!). The `input_name` and `experiment` inputs are added as columns to the output, to allow concatenation of outputs across multiple sample runs and easy grouping into `experiment` groups when plotting. 
* Added a simple docker with `samtools`, which is used in the above …
=> Added utilities for bam stats over intervals

ImputationPipeline/AggregatePRSResults.wdl, test/AggregatePRSResults/plumbing_data/condition_groups.tsv, test/AggregatePRSResults/test_AggregatePRSResults.wdl, test/AggregatePRSResults/test_AggregatePRSResults_json/test_plumbing_inputs.json
Three improvements:
1. Adds a check that samples are only scored for allowed combinations of conditions.  Displays the number of samples scored for each allowed condition grouping, as well as listing the samples for any unallowed condition groupings.
2. In PCA plot, differentiates (by color) samples with at least 1 high risk condition from those with none.
3. Makes the threshold at which a condition is visually flagged for an unexpected control sample value a parameter of the workflow (instead of being hardcoded as 0.12)
=> AggregatePRSResults updates

BenchmarkPhasing/BenchmarkPhasing.wdl, BenchmarkPhasing/PhaseVCF.wdl, BenchmarkPhasing/README.md, Utilities/Dockers/Bedtools/Dockerfile, Utilities/Dockers/README.md, Utilities/Dockers/WhatsHap/Dockerfile
As the title suggests, this PR contains the following:
- A workflow for phasing a VCF using an input bam with WhatsHap
- A workflow for benchmarking a phased VCF against a baseline using WhatsHap
- Some dockers to facilitate these new workflows
More detailed documentation can be found in the /BenchmarkPhasing/README.md. 
Note I haven't done much comparison across tools yet, so future development could include allowing the choice between WhatsHap and other phasing engines, similar to our old benchmarking script. For now I wanted to collect these together just to have something.
=> Added a pipeline for phasing VCFs and benchmarking their performance with WhatsHap

ImputationPipeline/ScoringPart.wdl, ImputationPipeline/ScoringTasks.wdl
A few improvements, and enabling scoring on hg38
1. plink needs to be explicitly told to allow `chr` on the beginning of chromosome names.  The pipeline now looks at the weights file to automatically determine the chromosome naming pattern that should be passed to plink.
2. an option is now available to code sites as `chr:pos:ref:alt` instead of `chr:pos:a1:a2` (where a1, a2 are in lexicographical order).  This allows indels to be included which could otherwise be ambiguous (if a vcf includes an A--> AA insertion and an AA --> A deletion at the same site, for example).  The default is still to use `chr:pos:a1:a2`, not because this is the encouraged method (it isn't and should be avoided if possible), but to avoid changing default behavior, at least for the time being.
3. there was a bug …
=> Update for PRS on hg38

ImputationPipeline/PRSWrapper.wdl
Addresses #67. 
Note that while it seems the `stop` function in R doesn't allow for custom error codes like `quit`, the default exit code for `stop` is still 1, so nothing has changed except the inclusion of some more helpful error messages.
=> Add error messages in R scripts rather than just quit for PRSWrapper

BenchmarkVCFs/BenchmarkVCFs.wdl
Added a variable to turn off the picard fingerprinting when running BenchmarkVCFs.wdl; please let me know if there are any issues or improvements to make!
Essentially, if the boolean 'fingerprint_toggle' is false, then the MatchEvalTruth task is skipped, but if the variable is true or blank then BenchmarkVCFs runs as usual.
Thank you!
-Dill :]
=> Dd toggle benchmark vc fs fingerprint

Utilities/WDLs/CreateIGVSession.wdl, Utilities/WDLs/README.md
A very short PR to add a utility for automating the process of creating an IGV session XML given (optional) list of bams, vcfs, or interval files (.interval_list or .bed). Also takes in a `ref_fasta` to customize the reference track. 
This is meant to replace a task used in `BenchmarkVCFs.wdl` and will be imported in a future version of our benchmarking scripts, but wanted to separate this task out so other folks can easily drop it into their workflows.
=> Add utility for creating IGV session from list of bams, vcfs, intervals

Utilities/WDLs/Interval2Bed.wdl, Utilities/WDLs/IntervalList2Bed.wdl, Utilities/WDLs/README.md
This short PR adds a utility that can convert a mix of `.interval_list` and `.bed` files into a list of just `.bed` files, which is ideal for pipelines using tools that only take in `.bed` files. The WDL is designed so that if all the inputs are `.bed` files, then no tasks are called (just some simple WDL code is run), and the original list and labels are returned. This means pipelines accepting just `.bed` files can use this task as a penalty-free (for `.bed` file users) way to extend their functionality to `.interval_list`s as well. The task also allows for optional label inputs so that labels can stay "next to" their converted file and used downstream. 
See the README in this PR for more details. This utility will be used in the upcoming benchmarking WDL and others.
=> Add utility for converting interval_list to bed efficiently

.circleci/config.yml, .dockstore.yml, Utilities/WDLs/MatchFingerprints.wdl, Utilities/WDLs/README.md
This PR adds a utility for handling various applications of fingerprinting. In particular, it should have functionality to perform the following:
* Act as a failsafe, allowing you to fail workflows when paired files don't match fingerprinting as expected;
* Allow you to match across all pairs in two lists of files, for when you might not be particularly sure of how to match up files due to known/suspected sample swaps, easy benchmarking truth-matching, or other cases;
* Give users the ability to toggle a few specific details, like forcing sample names to match in files, toggling the threshold for fingerprinting matches, etc.
It should be simple to drop into WDLs which require matched files for the same samples (like benchmarking query vs truth data), and use the resulting `matched_pairs` …
=> Add MatchFingerprints utility WDL

Utilities/WDLs/IntervalList2Bed.wdl
Updates the utility to convert `.interval_list` to `.bed` files to allow for `.gz` compressed input files. Currently the workflow will ignore / remove any files that end in `.gz`.
=> Update IntervalList2Bed to handle case of compressed interval file inputs

BenchmarkVCFs/BenchmarkVCFs.wdl, BenchmarkVCFs/CreateIGVSession.wdl, Utilities/Dockers/IGV-XML/Dockerfile, Utilities/Dockers/IGV-XML/writeIGV.sh
IGV xml writing currently uses a very old docker image hosted on Maddie's personal quay.io account.  This has recently led to test failures due to the deprecation of old docker image manifest schemes and (presumably) an upgrade in the version of docker run on cicle-ci machines (see https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1).  
I could not find a dockerfile for this docker anywhere, or even a copy of the `writeIGV.sh` script.  The references I could find all pointed to a google bucket that doesn't seem to exist anymore.  So I copied the script out of the old docker, and added into this repo, and created a new docker file and image for it.  I pushed the image to  `us-central1-docker.pkg.dev/broad-dsde-methods/hydro-gen-dockers/igv-xml:v1.0 …
=> Hotfix: Update IGV xml writing docker to get benchmark tests passing

GlimpseImputationPipeline/Glimpse2Imputation.wdl
need to keep stderr messages in stderr, since this is where cromwell checks for oom strings.
@michaelgatzen I think you were right and simplification is a better option than a complex fast fail here, give how rare to non-existent we believe this edge case to be.
=> Keep stderr consistent for OOM checks in Glimpse pipeline

ImputationPipeline/CreateAggregationSets/pyproject.toml, ImputationPipeline/ManualQCPRS/pyproject.toml
when building ManualCQPRS or CreateAggregationSets with pip, if new tags are added which match the git describe command but do not match the versioning regex, pip will fail.  To fix this, I changed the git_describe_command to match tags for the for `v[0-9]*`.  I don't think this is not a perfect fix, as there are still probably edge cases that could cause failure, but in practicality given the tagging and versioning practices we use, I think it is good enough.
=> Fix version parsing errors when building with pip

.dockstore.yml, Utilities/WDLs/PRSQC.wdl
- Satisfies basic requirements (`prs_score` and `full_model_score` thresholds/boundaries)
- Allows manual passing of controls
- Nice visual PCA QC output(s) which can be easily displayed on the google bucket page
- Input file format(s)/header(s)/etc. subject to change in future iterations
=> PRSQC WDL First Iteration

GlimpseImputationPipeline/Glimpse2Imputation.wdl, GlimpseImputationPipeline/Glimpse2ImputationAndCheckQC.wdl, GlimpseImputationPipeline/Glimpse2ImputationInBatches.wdl, GlimpseImputationPipeline/Glimpse2MergeBatches.wdl, GlimpseImputationPipeline/Glimpse2SplitReference.wdl, GlimpseImputationPipeline/README.md, GlimpseImputationPipeline/glimpse_docker/build_base_and_extension_docker.sh, test/Glimpse2Imputation/test_outputs.json
- Added `mem_scaling_factor_phase` for adjusting memory requirements when running in single sample mode
- Updated GLIMPSE2 docker to most recent version from official repo
- Removed monitoring log output, since Terra now has this feature built in
- Added default value for `interval_list` in `Glimpse2MergeBatches`
- Updated documentation in README
- Added automatic tagging in for docker generation script
- Had to rename the `die` function in the shell script to `end_program` because Github Copilot would refuse to do anything in that script
=> GLIMPSE2 improvements

Utilities/Dockers/README.md, Utilities/Dockers/VCFEval/Dockerfile, Utilities/Dockers/VCFEval/Dockerfile_tmp
Just adding some extra documentation for the `vcfeval_docker:v1.1` used for an intern project this summer.
=> Update vcfeval docker image

GlimpseImputationPipeline/Glimpse2ImputationAndCheckQC.wdl
I told @kachulis that we'd made a small update to the glimpse wdl to wire the phasing cpu/mem into the outer WDL. This PR recapitulates that update.
=> Wire Glimpse phasing runtime params into outer workflow

gCNV/cnv_germline_case_filter_workflow.wdl, test/choose_watt_tests/choose_watt_tests.py
Fixes a bug in the panel count calculation, and additionally improves it.
Previously, events in a case sample were matched to events in the panel by the following algorithm:
1. label each event in the case sample and panel which the list of exons it overlaps.
2. For an event in the case sample, a sample in the panel is considered to contain the same event in the fraction of exons overlapped by the event which are also overlapped by events of the same type in the panel sample is greater than a specified "overlap threshold"
The bug was that when labeling events with exons, an event was considered to overlap an exon only if it overlapped the start of the exon.  This meant that if, for example, and event started part way through an exon, it would not be labeled with that exon.
This PR firstly …
=> Fix and improve panel count calculation in gcnv filtering

.github/workflows/run_tests.yaml, test/simple_cromwell.conf
PAPIv2 will be [unavailable after July 8, 2025](https://cloud.google.com/life-sciences/docs/how-tos/migration).  We will need to migrate our tests to GCPBatch.
Leaving PAPIv2 option in cromwell config, but moving tests to run on GCPBatch.  We can remove PAPIv2 completely from the config if this change appears to be working fine for a while.
=> Move tests to GCPBatch

README.md, Utilities/Dockers/Python-Data-Slim/Dockerfile
[`package_index` was recently removed from setuptools](https://github.com/pypa/setuptools/pull/4963#issuecomment-2851940964), but is used in firecloud `setup.py`, so installing firecloud in the docker fails.  
fix is to install older version of setuptools, and then force pip to use the installed version of setup tools with the [`--no-build-isolation`](https://github.com/pypa/setuptools/discussions/4354) option.
=> Fix Python-Data-Slim Dockerfile

GlimpseImputationPipeline/DeliverGlimpseCohort/DeliverGlimpseCohort.py
prior to python3.12, quote reuse in f-strings raises a syntax error.  https://docs.python.org/3.12/whatsnew/3.12.html#pep-701-syntactic-formalization-of-f-strings
this PR is so script will run correctly for versions older than 3.12 (but newer than 3.6)
=> f-string for older versions of python
